### ISSUE TITLE
DisplayMapName 1.1

### ISSUE THREAD

**Issue by franckentien** [openplanet-nl/plugin-signing#10]
Hello, 

I fix the bug with the last update and change structure to OP file.

Can you sign it to me ? 

Thanks.

## Where can we find the plugin?
* https://openplanet.nl/files/89
* https://github.com/franckentien/TM2020-Openplanet-DisplayMapName

## Has your plugin been signed previously?

* Yes but without op structure 

## Attach your plugin

[DisplayMapName.zip](https://github.com/openplanet-nl/plugin-signing/files/6758968/DisplayMapName.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[DisplayMapName.zip](https://github.com/openplanet-nl/plugin-signing/files/6759136/DisplayMapName.zip)

**Comment by franckentien** [comment]
thanks
