### ISSUE TITLE
EditorHelpers 4.1

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/plugin-signing#100]
## Where can we find the plugin?
https://openplanet.nl/files/69
https://github.com/skybaks/editor-helpers

## Has your plugin been signed previously?
yes

## Attach your plugin
[EditorHelpers.zip](https://github.com/openplanet-nl/plugin-signing/files/7271594/EditorHelpers.zip)

## Changes since last signature
* Fixed a bug in setting some placement params
* Added a new editor function for custom hotkeys. Added one hotkey for toggling airblock mode

**Comment by codecat** [comment]
Looks good! 👍 

[EditorHelpers.zip](https://github.com/openplanet-nl/plugin-signing/files/7273622/EditorHelpers.zip)
