### ISSUE TITLE
Ghost Scrubber 1.1.0

### ISSUE THREAD

**Issue by boofat** [openplanet-nl/plugin-signing#101]
## Where can we find the plugin?
https://openplanet.nl/files/136

## Has your plugin been signed previously?
yes ish

## Attach your plugin
[GhostScrubber.zip](https://github.com/openplanet-nl/plugin-signing/files/7272337/GhostScrubber.zip)

This version uses Dev::InterceptProc to alter the game script's behaviour to work with the new records spectating, if that's an issue.

**Comment by codecat** [comment]
Interesting, those proc interceptions, hope it's stable! 🤞

[GhostScrubber.zip](https://github.com/openplanet-nl/plugin-signing/files/7273629/GhostScrubber.zip)
