### ISSUE TITLE
NitroDashboard v1.3.0

### ISSUE THREAD

**Issue by nitroquery** [openplanet-nl/plugin-signing#105]
## Where can we find the plugin?

- https://github.com/nitroquery/NitroDashboard/releases/tag/v1.3.0

## Has your plugin been signed previously?
- [x] yes

**Comment by codecat** [comment]
👍 

[NitroDashboard.zip](https://github.com/openplanet-nl/plugin-signing/files/7315847/NitroDashboard.zip)
