### ISSUE TITLE
Evo - Servers and Socials v1.2

### ISSUE THREAD

**Issue by Chris92de** [openplanet-nl/plugin-signing#11]
## Where can we find the plugin?
https://openplanet.nl/files/104

## Has your plugin been signed previously?
Yes

## Attach your plugin
[Evo.zip](https://github.com/openplanet-nl/plugin-signing/files/6760492/Evo.zip)

**Comment by codecat** [comment]
Looks good 👍 

[Evo.zip](https://github.com/openplanet-nl/plugin-signing/files/6760601/Evo.zip)
