### ISSUE TITLE
Ghost Scrubber 1.1.1

### ISSUE THREAD

**Issue by boofat** [openplanet-nl/plugin-signing#111]
## Where can we find the plugin?
https://openplanet.nl/files/136

## Has your plugin been signed previously?
yes

## Attach your plugin
[GhostScrubber.zip](https://github.com/openplanet-nl/plugin-signing/files/7349827/GhostScrubber.zip)

**Comment by codecat** [comment]
Sorry for the delay, feel free to ping me next time if I forget 👍 

[GhostScrubber.zip](https://github.com/openplanet-nl/plugin-signing/files/7359536/GhostScrubber.zip)
