### ISSUE TITLE
Reminder 1.1

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#114]
## Where can we find the plugin?
https://openplanet.nl/files/125

## Has your plugin been signed previously?
yes

## Attach your plugin
[reminder.zip](https://github.com/openplanet-nl/plugin-signing/files/7449277/reminder.zip)

Updated to CET

**Comment by codecat** [comment]
👍 

[Reminder.zip](https://github.com/openplanet-nl/plugin-signing/files/7449675/Reminder.zip)
