### ISSUE TITLE
MX Randomizer 1.7.4

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#117]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7490780/MXRandom.zip)

**Comment by codecat** [comment]
Looks good 👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7490806/MXRandom.zip)
