### ISSUE TITLE
LightmapQuality 1.2

### ISSUE THREAD

**Issue by AmazingBeu** [openplanet-nl/plugin-signing#119]
## Plugin description
https://openplanet.nl/files/137

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
yes

## Did you use `Permissions.as`?
no

## Attach your plugin
[LightmapQuality.zip](https://github.com/openplanet-nl/plugin-signing/files/7501039/LightmapQuality.zip)

## Changelog :
Add a block counter to track progress during selection

**Comment by codecat** [comment]
👍 

[LightmapQuality.zip](https://github.com/openplanet-nl/plugin-signing/files/7505203/LightmapQuality.zip)
