### ISSUE TITLE
TM.io Link Plugin Update Signature Request

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/plugin-signing#12]
## Where can we find the plugin?
https://openplanet.nl/files/65
https://github.com/skybaks/tm-io-link

## Has your plugin been signed previously?
yes

## Attach your plugin
[TmIoLink.zip](https://github.com/openplanet-nl/plugin-signing/files/6766314/TmIoLink.zip)

**Comment by codecat** [comment]
Looks good 👍 

[TmIoLink.zip](https://github.com/openplanet-nl/plugin-signing/files/6768728/TmIoLink.zip)
