### ISSUE TITLE
Ranked Total Points 0.9

### ISSUE THREAD

**Issue by Zurite** [openplanet-nl/plugin-signing#122]
## Plugin description
Displays a widget in game that shows every players total score in Matchmaking/Ranked.

This allows you to keep track of the MVP and how close each player is to each other.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[RankedTotalPoints.zip](https://github.com/openplanet-nl/plugin-signing/files/7525193/RankedTotalPoints.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[RankedTotalPoints.zip](https://github.com/openplanet-nl/plugin-signing/files/7538812/RankedTotalPoints.zip)
