### ISSUE TITLE
Editor Helpers 4.4

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/plugin-signing#123]
## Where can we find the plugin?
https://github.com/skybaks/tm-editor-helpers

## Has your plugin been signed previously?
yes

## Attach your plugin
[EditorHelpers.zip](https://github.com/openplanet-nl/plugin-signing/files/7532713/EditorHelpers.zip)

## Whats changed since last signing
* Clean up 'Hotkey function' code and add hotkey to cycle through block colors
* Refactor files to organize the repo
* Add back support for MP4
* Add item pivot position manipulation to custom item function

**Comment by codecat** [comment]
👍 

[EditorHelpers.zip](https://github.com/openplanet-nl/plugin-signing/files/7538822/EditorHelpers.zip)
