### ISSUE TITLE
Split Speeds

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/plugin-signing#124]
## Plugin description
Shows your speed and speed difference compared to your personal best at checkpoint splits.
https://i.imgur.com/w05amp0.png

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7535630/SplitSpeeds.zip)
(edited the zip 2021-11-15T03:16:12.075Z to add a setting)

**Comment by codecat** [comment]
Looks good! 👍 

[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7538861/SplitSpeeds.zip)
