### ISSUE TITLE
Split Speeds update

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/plugin-signing#125]
## Where can we find the plugin?
https://openplanet.nl/files/145

## Has your plugin been signed previously?
yes

## Attach your plugin
[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7560057/SplitSpeeds.zip)

edited again.. (2021-11-18T05:02:54.776Z)

**Comment by codecat** [comment]
Sorry for the delay 👍 

[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7572964/SplitSpeeds.zip)
