### ISSUE TITLE
Ranked Total Points 1.0

### ISSUE THREAD

**Issue by Zurite** [openplanet-nl/plugin-signing#126]
## Where can we find the plugin?
[OpenPlanet page](https://openplanet.nl/files/144)

[Github page](https://github.com/Zurite/Ranked-Total-Points)

## Has your plugin been signed previously?
yes

## Attach your plugin
[RankedTotalPoints.zip](https://github.com/openplanet-nl/plugin-signing/files/7551492/RankedTotalPoints.zip)

**Comment by codecat** [comment]
Sorry for the delay 👍 

[RankedTotalPoints.zip](https://github.com/openplanet-nl/plugin-signing/files/7572965/RankedTotalPoints.zip)
