### ISSUE TITLE
No-Respawn Timer

### ISSUE THREAD

**Issue by AnfR82** [openplanet-nl/plugin-signing#127]
## Plugin description
When you start respawning during a run, it displays a timer close to the offical one (on the bottom) which gives the time you could have made without respawning.
At the end of the run, it also displays the number of respawn and the medal you could have win.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[NoRespawnTimer.zip](https://github.com/openplanet-nl/plugin-signing/files/7566372/NoRespawnTimer.zip)

**Comment by AnfR82** [comment]
This screen shot is what is displayed at the end of the run.

![EndRun](https://user-images.githubusercontent.com/94650759/142506496-83688207-dc55-495f-b3d4-1d4a5efdce56.jpg)

In this case, the player knows that without the 2 respawns, he would have reach the silver medal.

During the run, only the timer is displayed.

**Comment by codecat** [comment]
Nice one! 👍 

[NoRespawnTimer.zip](https://github.com/openplanet-nl/plugin-signing/files/7572952/NoRespawnTimer.zip)
