### ISSUE TITLE
SplitSpeeds update 0.2.7

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/plugin-signing#128]
## Where can we find the plugin?
https://openplanet.nl/files/145

## Has your plugin been signed previously?
yes

## Attach your plugin
[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7573819/SplitSpeeds.zip)

**Comment by codecat** [comment]
👍 

[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7574493/SplitSpeeds.zip)
