### ISSUE TITLE
Split Speeds update 0.2.9

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/plugin-signing#129]
## Where can we find the plugin?
https://openplanet.nl/files/145

## Has your plugin been signed previously?
yes

## Attach your plugin
[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7576926/SplitSpeeds.zip)
edited 2021-11-21T19:27:14.365Z lil' bug
last update in a while hopefully, unless someone finds bugs

**Comment by codecat** [comment]
Looks good 👍 

[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7603169/SplitSpeeds.zip)
