### ISSUE TITLE
Update Plugin Signature Request: Editor Helpers

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/plugin-signing#13]
## Where can we find the plugin?
https://openplanet.nl/files/69
https://github.com/skybaks/editor-helpers

## Has your plugin been signed previously?
yes

## Attach your plugin
[EditorHelpers.zip](https://github.com/openplanet-nl/plugin-signing/files/6766318/EditorHelpers.zip)

**Comment by codecat** [comment]
Looks good 👍 

[EditorHelpers.zip](https://github.com/openplanet-nl/plugin-signing/files/6768751/EditorHelpers.zip)
