### ISSUE TITLE
No-Respawn Timer

### ISSUE THREAD

**Issue by AnfR82** [openplanet-nl/plugin-signing#130]
## Where can we find the plugin?
attached

## Has your plugin been signed previously?
Yes

## Attach your plugin
[NoRespawnTimer.zip](https://github.com/openplanet-nl/plugin-signing/files/7576102/NoRespawnTimer.zip)

Fix : issue with timer in online mode with hidden HUD

**Comment by codecat** [comment]
Looks good 👍 

[NoRespawnTimer.zip](https://github.com/openplanet-nl/plugin-signing/files/7603206/NoRespawnTimer.zip)
