### ISSUE TITLE
Twitch Base 2.0

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#134]
## Where can we find the plugin?
https://openplanet.nl/files/93

## Has your plugin been signed previously?
yes

## Attach your plugin
[TwitchBase.zip](https://github.com/openplanet-nl/plugin-signing/files/7654722/TwitchBase.zip)

**Comment by codecat** [comment]
👍 

[TwitchBase.zip](https://github.com/openplanet-nl/plugin-signing/files/7730948/TwitchBase.zip)
