### ISSUE TITLE
Chat Viewer 1.0

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#135]
## Where can we find the plugin?
https://openplanet.nl/files/95

## Has your plugin been signed previously?
yes

## Attach your plugin
[ChatViewer.zip](https://github.com/openplanet-nl/plugin-signing/files/7654725/ChatViewer.zip)

**Comment by codecat** [comment]
Modified the name in `info.toml` and the name in `RenderMenu` to avoid any possible ambiguity ("Chat Viewer" is maybe a bit too generic name).

[TwitchChatViewer.zip](https://github.com/openplanet-nl/plugin-signing/files/7730960/TwitchChatViewer.zip)
