### ISSUE TITLE
Chat Inspector 1.0

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#136]
## Where can we find the plugin?
https://openplanet.nl/files/94

## Has your plugin been signed previously?
yes

## Attach your plugin
[ChatInspector.zip](https://github.com/openplanet-nl/plugin-signing/files/7654726/ChatInspector.zip)

**Comment by codecat** [comment]
Changed the name in info.toml and in Render & RenderMenu.

[TwitchChatInspector.zip](https://github.com/openplanet-nl/plugin-signing/files/7730968/TwitchChatInspector.zip)
