### ISSUE TITLE
Reminder 1.2

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#138]
## Where can we find the plugin?
https://openplanet.nl/files/125

## Has your plugin been signed previously?
yes

## Attach your plugin
[reminder.zip](https://github.com/openplanet-nl/plugin-signing/files/7674199/reminder.zip)

**Comment by codecat** [comment]
👍 

[Reminder.zip](https://github.com/openplanet-nl/plugin-signing/files/7676660/Reminder.zip)
