### ISSUE TITLE
In Game Clock

### ISSUE THREAD

**Issue by sephirothx** [openplanet-nl/plugin-signing#139]
## Plugin description
A customizable clock displayed where you want and when you want, so at least you know what time it is when you play Trackmania all night.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[InGameClock.zip](https://github.com/openplanet-nl/plugin-signing/files/7697074/InGameClock.zip)

**Comment by codecat** [comment]
Looks good 👍 

[InGameClock.zip](https://github.com/openplanet-nl/plugin-signing/files/7698964/InGameClock.zip)
