### ISSUE TITLE
Updated Signature on Widescreen UI Fix

### ISSUE THREAD

**Issue by Eierpflanze** [openplanet-nl/plugin-signing#14]
## Where can we find the plugin?
https://openplanet.nl/files/76

## Has your plugin been signed previously?
Yes

## Attach your plugin
[Plugin_WidescreenFix.zip](https://github.com/openplanet-nl/plugin-signing/files/6775931/Plugin_WidescreenFix.zip)

**Comment by codecat** [comment]
Looks good 👍 

[Plugin_WidescreenFix.zip](https://github.com/openplanet-nl/plugin-signing/files/6776094/Plugin_WidescreenFix.zip)
