### ISSUE TITLE
Chat Button Bar V 1.1

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#140]
## Where can we find the plugin?
[[...]](https://openplanet.nl/files/115)

## Has your plugin been signed previously?
yes

## Attach your plugin
[ChatButtonBar.zip](https://github.com/openplanet-nl/plugin-signing/files/7697486/ChatButtonBar.zip)

## Changes
NitroQuery told me, that I always ask in RenderInterface for the Permission. Now I ask it one time initial in the Main-Method.

**Comment by codecat** [comment]
You forgot to change the version in `info.toml` to `1.1`. I've changed it for you and signed it 👍

[ChatButtonBar.zip](https://github.com/openplanet-nl/plugin-signing/files/7698969/ChatButtonBar.zip)

**Comment by DennisWillers** [comment]
Thanks! :)
