### ISSUE TITLE
Presets and Sharing

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/plugin-signing#141]
## Plugin description
Using the Meta API this plugin reads other plugins settings into a custom serialization format and outputs as a base64 string. Then upon user activation, these serialized settings can be re-applied to a plugin.
Furthermore, this plugin maintains a list of "presets" which are defined as a serialized text associated to a particular plugin ID and a list of "loadouts" which are defined as a grouping of presets to be activated together.
Due to the dynamic nature of creating any number of "presets" or "loadouts" the plugin maintains its own settings file called PresetsAndSharing.json in the OpenplanetNext directory.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
No, I did not provide any permission check of any kind. This plugin does not interact directly with the game. I don't make a single call to GetApp(). If you think it would be appropriate to include some kind of permissions check I would be happy to make changes per your direction.

## Did you use `Permissions.as`?
No, see above.

## Attach your plugin
https://github.com/skybaks/tm-presetsandsharing
[PresetsAndSharing.zip](https://github.com/openplanet-nl/plugin-signing/files/7699296/PresetsAndSharing.zip)

**Comment by codecat** [comment]
Nice! 👍 

[PresetsAndSharing.zip](https://github.com/openplanet-nl/plugin-signing/files/7703296/PresetsAndSharing.zip)
