### ISSUE TITLE
Load Map with URL

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#142]
## Plugin description
This is a quick plugin I've done to simply load a map with its URL, useful for not downloading the map and for map build collabs.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
yes

## Did you use `Permissions.as`?
yes

## Attach your plugin
[LoadMapURL.zip](https://github.com/openplanet-nl/plugin-signing/files/7737458/LoadMapURL.zip)

**Comment by codecat** [comment]
👍 

[LoadMapURL.zip](https://github.com/openplanet-nl/plugin-signing/files/7738411/LoadMapURL.zip)
