### ISSUE TITLE
AFK Queue Tool 2.2

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#143]
## Where can we find the plugin?
https://openplanet.nl/files/71

## Has your plugin been signed previously?
yes

## Attach your plugin
[AFKQueue.zip](https://github.com/openplanet-nl/plugin-signing/files/7738376/AFKQueue.zip)

**Comment by codecat** [comment]
👍 

[AFKQueue.zip](https://github.com/openplanet-nl/plugin-signing/files/7738416/AFKQueue.zip)
