### ISSUE TITLE
Logger library for Plugin Scripts.

### ISSUE THREAD

**Issue by IGI-Research-Devs** [openplanet-nl/plugin-signing#144]
## Plugin description
[This is simple logger library for open-planet plugin scripts.]

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
[no]

## Did you use `Permissions.as`?
[no]

##
 Attach your plugin
[Logger.zip](https://github.com/openplanet-nl/plugin-signing/files/7741622/Logger.zip)

**Comment by codecat** [comment]
Nice, but as a plugin, this plugin doesn't really do anything. Did you meant to add an `info.toml`?

**Comment by IGI-Research-Devs** [comment]
> Nice, but as a plugin, this plugin doesn't really do anything. Did you meant to add an `info.toml`?

I have added **info.toml** now, and this provide functionality to developers only.

**Comment by codecat** [comment]
As a plugin though, it does nothing. The `info.toml` isn't useful, so I'm not sure why you added it. As a library, I'm sure it's useful, but then you don't need to turn this into a plugin, especially considering you have no exports.

**Comment by IGI-Research-Devs** [comment]
okay no worries i will add them in my next plugin
