### ISSUE TITLE
Frames manager 

### ISSUE THREAD

**Issue by haseeb-heaven** [openplanet-nl/plugin-signing#146]
## Plugin description
[Frames manager to manage Game Frames with different modes and Customizable UI.]

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
[no]

## Did you use `Permissions.as`?
[no]

## Attach your plugin
[FramesManager.zip](https://github.com/openplanet-nl/plugin-signing/files/7756804/FramesManager.zip)

**Comment by codecat** [comment]
👍 

[FramesManager.zip](https://github.com/openplanet-nl/plugin-signing/files/7771836/FramesManager.zip)
