### ISSUE TITLE
ManiaExchange

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#147]
## Plugin description
The ManiaExchange menu that I teased since a while on Discord 😂 

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
yes

## Did you use `Permissions.as`?
yes

## Attach your plugin
[ManiaExchange.zip](https://github.com/openplanet-nl/plugin-signing/files/7758939/ManiaExchange.zip)

**Comment by codecat** [comment]
Sorry for the delay 👍 

[ManiaExchange.zip](https://github.com/openplanet-nl/plugin-signing/files/7771825/ManiaExchange.zip)
