### ISSUE TITLE
TMRL grab data

### ISSUE THREAD

**Issue by yannbouteiller** [openplanet-nl/plugin-signing#15]
## Plugin description
Broadcasts some data from OpenPlanet on localhost (tmrl project)

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no (starter perms)

## Did you use `Permissions.as`?
no

## Attach your plugin
[Plugin_GrabData_0_1.zip](https://github.com/openplanet-nl/plugin-signing/files/6835246/Plugin_GrabData_0_1.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[Plugin_GrabData_0_1.zip](https://github.com/openplanet-nl/plugin-signing/files/6835314/Plugin_GrabData_0_1.zip)

**Comment by yannbouteiller** [comment]
Thanks :)
