### ISSUE TITLE
[New Plugin] Nytely Finish Time Predictor

### ISSUE THREAD

**Issue by JackNytely** [openplanet-nl/plugin-signing#153]
## Plugin description
A simple, but highly accurate, in game timer to give you a prediction on the time you will get on your current run.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
No

## Did you use `Permissions.as`?
No

## Attach your plugin
[NytelyFinishTimePredictor.zip](https://github.com/openplanet-nl/plugin-signing/files/7792643/NytelyFinishTimePredictor.zip)

**Comment by codecat** [comment]
This doesn't look right:

```asc
void RenderMenu() {
	if (UI::MenuItem("\\$09f" + Icons::Flag + "\\$z Checkpoint Counter", "", showTimer)) {
		showTimer = !showTimer;
	}
}
```

**Comment by JackNytely** [comment]
> This doesn't look right:
> 
> ```c++
> void RenderMenu() {
> 	if (UI::MenuItem("\\$09f" + Icons::Flag + "\\$z Checkpoint Counter", "", showTimer)) {
> 		showTimer = !showTimer;
> 	}
> }
> ```

You are correct, thanks for pointing that out to me. Here is the Updated Code

[NytelyFinishTimePredictor.zip](https://github.com/openplanet-nl/plugin-signing/files/7792800/NytelyFinishTimePredictor.zip)

**Comment by codecat** [comment]
👍 

[NytelyFinishTimePredictor.zip](https://github.com/openplanet-nl/plugin-signing/files/7792895/NytelyFinishTimePredictor.zip)
