### ISSUE TITLE
[New Plugin] Predictor

### ISSUE THREAD

**Issue by JackNytely** [openplanet-nl/plugin-signing#155]
## Plugin description
A simple, but highly accurate, in game timer to give you a prediction on the time you will get on your current run.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
No

## Did you use `Permissions.as`?
No

## Attach your plugin
[Predictor.zip](https://github.com/openplanet-nl/plugin-signing/files/7797037/Predictor.zip)

**Comment by codecat** [comment]
Sorry, taking a bit of a break for New Years :) will check this soon!

**Comment by JackNytely** [comment]
> Sorry, taking a bit of a break for New Years :) will check this soon!

No worries, thanks for everything and I truly hope you have a wonderful new year

**Comment by codecat** [comment]
👍 

[Predictor.zip](https://github.com/openplanet-nl/plugin-signing/files/7797780/Predictor.zip)

**Comment by JackNytely** [comment]
> 👍
> 
> [Predictor.zip](https://github.com/openplanet-nl/plugin-signing/files/7797780/Predictor.zip)

When I attempt to rename the zip file to op it gives me this error 
![image](https://user-images.githubusercontent.com/48361205/147858354-c31c903e-f814-40fc-96ca-9529e02ad8df.png)

**Comment by codecat** [comment]
That's because the zip contains an .op file

**Comment by JackNytely** [comment]
> That's because the zip contains an .op file

Thankyou very much.

Have an amazing day and New Year ^_^/
