### ISSUE TITLE
Track Generator 0.8

### ISSUE THREAD

**Issue by AvondaleZPR** [openplanet-nl/plugin-signing#156]
## Plugin description
It generates random tracks.
Even in the simple editor! using blocks that are not available in the simple editor, i hope thats not a problem...

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
No

## Did you use `Permissions.as`?
No

## Attach your plugin
[TrackGenerator.zip](https://github.com/openplanet-nl/plugin-signing/files/7797932/TrackGenerator.zip)

**Comment by codecat** [comment]
> Even in the simple editor! using blocks that are not available in the simple editor, i hope thats not a problem...

Yeah, that'd be a problem.. advanced editor is available starting from Standard Edition, right? So you'd still want this signed, but it needs to not be available in the simple editor.

**Comment by AvondaleZPR** [comment]
but why if its only gonna be available to standart+?

**Comment by AvondaleZPR** [comment]
or if this could be in free version i can disable blocks that arent available

**Comment by AvondaleZPR** [comment]
[TrackGenerator.zip](https://github.com/openplanet-nl/plugin-signing/files/7798291/TrackGenerator.zip)
now it uses permissions (OpenAdvancedMapEditor) and disables blocks like cruise or super turbo

**Comment by codecat** [comment]
It's kinda difficult to maintain a list of "simple editor blocks", so I'd prefer if it only would be available in the advanced editor.

By the way, I'd recommend changing `"Riolu Block"`, it's not really descriptive of what the actual block is, plus everyone has kinda moved on already.

**Comment by AvondaleZPR** [comment]
i dont understand how it works then. starter edition users can download plugins for standart+ and it will work, unless it has manual check for permissions?
its not about blocks but about block styles. flat tech, flat dirt, flat sausage and flat ice with wall is all simple editor has, with 2 pages of blocks for each style.
![image](https://user-images.githubusercontent.com/26060995/148124883-18668db0-13a9-428d-8eae-5badc1d5fb97.png)
![image](https://user-images.githubusercontent.com/26060995/148124894-63bf5cde-e269-415f-9a5e-a07bdbf12601.png)

**Comment by codecat** [comment]
Yes, signed plugins should always be checking for appropriate permissions.

What happens if Nadeo ever changes which blocks are available though? Now your plugin is inconsistent. It's not a huge deal, but it's something I'd rather want to avoid. Gotta future-proof stuff a bit!

**Comment by AvondaleZPR** [comment]
if only they will remove blocks, which is unlikely. 
i dont think having a chance nadeo will update simple editor blocks(which i think they never did since the relase of the game) is enough to prevent a lot of players without standard acsess from using this. but if you absolutley sure this is the only way then ok

**Comment by codecat** [comment]
Thought about it some more, and I think it's ok!

👍 

[TrackGenerator.zip](https://github.com/openplanet-nl/plugin-signing/files/7833498/TrackGenerator.zip)
