### ISSUE TITLE
Signing SpecPicker

### ISSUE THREAD

**Issue by Monkeypac** [openplanet-nl/plugin-signing#16]
## Plugin description
The plugin is already uploaded on the site [here](https://openplanet.nl/files/77).

It's a really simple plugin that allows to quickly search and spectate a player on the current server.

My usage of the API might be messy so, sorry for that.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[SpecPicker.zip](https://github.com/openplanet-nl/plugin-signing/files/6836968/SpecPicker.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[Plugin_SpecPicker.zip](https://github.com/openplanet-nl/plugin-signing/files/6840014/Plugin_SpecPicker.zip)
