### ISSUE TITLE
TrackGenerator 0.8.1

### ISSUE THREAD

**Issue by AvondaleZPR** [openplanet-nl/plugin-signing#160]
## Where can we find the plugin?
https://openplanet.nl/files/156

## Has your plugin been signed previously?
yes

## Attach your plugin
[TrackGenerator.zip](https://github.com/openplanet-nl/plugin-signing/files/7869064/TrackGenerator.zip)

fixed a crash on startup, only ui.as and info.toml files have changed, if that helps

**Comment by codecat** [comment]
Please change this line to remove "Riolu Block" and change it to "Slowmo Block" instead:
```asc
slowmotion = UI::Checkbox("Riolu Block", slowmotion); UI::SameLine();
```

**Comment by AvondaleZPR** [comment]
[TrackGenerator.zip](https://github.com/openplanet-nl/plugin-signing/files/7870222/TrackGenerator.zip)

**Comment by codecat** [comment]
Thanks! 👍 

[TrackGenerator.zip](https://github.com/openplanet-nl/plugin-signing/files/7874690/TrackGenerator.zip)
