### ISSUE TITLE
Tweaker 0.02

### ISSUE THREAD

**Issue by fentras** [openplanet-nl/plugin-signing#161]
## Where can we find the plugin?
https://github.com/fentras-labs/op-tweaker
https://openplanet.nl/files/126

## Has your plugin been signed previously?
Yes

## Attach your plugin
[Tweaker v0.02.zip](https://github.com/openplanet-nl/plugin-signing/files/7869584/Tweaker.v0.02.zip)

**Comment by codecat** [comment]
👍 

[Tweaker.zip](https://github.com/openplanet-nl/plugin-signing/files/7874694/Tweaker.zip)
