### ISSUE TITLE
Split Speeds 0.3.0

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/plugin-signing#164]
Fix finding pb ghost with other languages

## Where can we find the plugin?
https://openplanet.nl/files/145

## Has your plugin been signed previously?
yes

## Attach your plugin
[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7884891/SplitSpeeds.zip)

**Comment by codecat** [comment]
👍 

[SplitSpeeds.zip](https://github.com/openplanet-nl/plugin-signing/files/7916247/SplitSpeeds.zip)
