### ISSUE TITLE
Advanced Free Block Mode

### ISSUE THREAD

**Issue by schl3ck** [openplanet-nl/plugin-signing#17]
## Plugin description
This plugin allows you to precisely place blocks in the _free_ mode. It can move and rotate the block pixel perfect in every direction via the global coordinate system or a local one that is rotated with the block.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
No

## Did you use `Permissions.as`?
Yes. To check if the player can create/edit a map.

## Attach your plugin
[AdvancedFreeBlockMode.zip](https://github.com/openplanet-nl/plugin-signing/files/6857082/AdvancedFreeBlockMode.zip)

Off topic question: Where is the best to file bug reports with AngelScript in Openplanet? On your discord server?
I'm asking because the `Math::Angle(vec3, vec3)` function is returning a wrong result.

**Comment by schl3ck** [comment]
I've removed debug code and cleaned it up a bit. Hopefully you haven't started signing yet.
[AdvancedFreeBlockMode.zip](https://github.com/openplanet-nl/plugin-signing/files/6857160/AdvancedFreeBlockMode.zip)

**Comment by schl3ck** [comment]
Another hotfix. Sorry!
[AdvancedFreeBlockMode.zip](https://github.com/openplanet-nl/plugin-signing/files/6857215/AdvancedFreeBlockMode.zip)

**Comment by codecat** [comment]
Sorry this took a while! Looks good! 👍 

[AdvancedFreeBlockMode.zip](https://github.com/openplanet-nl/plugin-signing/files/6871235/AdvancedFreeBlockMode.zip)

To answer your question, yeah Discord is probably the best place. Thanks for the report though, I'll have to check it out! I tried matching the Maniascript implementation of those vector functions, but I guess I made some mistakes. 😅

**Comment by codecat** [comment]
Btw, you should probably add a site ID to the `info.toml` file now that it's uploaded on the website. (Will require a re-sign of the toml file though)

**Comment by schl3ck** [comment]
Yeah, I thought about that. Thanks!

I'll just append it here if it's alright?

[AFBM-info-toml.zip](https://github.com/openplanet-nl/plugin-signing/files/6872462/AFBM-info-toml.zip)

**Comment by codecat** [comment]
Yeah that's good! Here's the new signature.

[AFBM-info-signed.zip](https://github.com/openplanet-nl/plugin-signing/files/6872522/AFBM-info-signed.zip)

I keep realizing the site ID in the `info.toml` file isn't very flexible, so maybe I will get rid of it in the future. Will see!

**Comment by codecat** [comment]
Are you on Discord, by the way? I just noticed an Openplanet bug due to your use of static initializers for font loading (which only causes problems on the packaged `.op` version). I've fixed those bugs in Openplanet and will release an update soon. 👍
