### ISSUE TITLE
ItemExchange

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/plugin-signing#171]
## Plugin description
Browse IX and import items/sets into the editor without having to restart the game. This op file does not have the DLL included, the plugin recognizes this and doesn't load the lib, when importing an item it just tells the user to click twice.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
yes, perms="paid"

## Did you use `Permissions.as`?
yes, to check if the user has advanced editor access before being allowed to import (import wouldn't work with simple editor anyways)

## Attach your plugin
[ItemExchange.zip](https://github.com/openplanet-nl/plugin-signing/files/7955812/ItemExchange.zip)

**Comment by codecat** [comment]
Hey sorry for the delay..

> This op file does not have the DLL included

The code for this still exists in the code and is actively called, perhaps that should be removed?

**Comment by RuurdBijlsma** [comment]
I have it like that because my own version still uses the dll and I don't really want to keep 2 versions of the code 🤔

**Comment by codecat** [comment]
Ok 👍 

[ItemExchange.zip](https://github.com/openplanet-nl/plugin-signing/files/7985693/ItemExchange.zip)

**Comment by codecat** [comment]
Sorry, don't upload this yet, I gave you invalid signatures.

**Comment by codecat** [comment]
This one is correct 👍 

[ItemExchange.zip](https://github.com/openplanet-nl/plugin-signing/files/7985829/ItemExchange.zip)
