### ISSUE TITLE
grinding stats 1.4

### ISSUE THREAD

**Issue by drekdrek** [openplanet-nl/plugin-signing#172]
## Where can we find the plugin?
[[...]](https://openplanet.nl/files/158)

## Has your plugin been signed previously?
yes
## Attach your plugin
[Grinding Stats.zip](https://github.com/openplanet-nl/plugin-signing/files/7936482/Grinding.Stats.zip)

## Changes
- remade saving function
- separated rendering to another file

**Comment by codecat** [comment]
👍 

[GrindingStats.zip](https://github.com/openplanet-nl/plugin-signing/files/7965920/GrindingStats.zip)
