### ISSUE TITLE
Ultrawide UI fix v2.0

### ISSUE THREAD

**Issue by Eierpflanze** [openplanet-nl/plugin-signing#173]
## Where can we find the plugin?
[GitHub](https://github.com/Eierpflanze/tm2020-ultrawide-ui-fix/tree/v2.0-unsigned)
[Openplanet](https://openplanet.nl/files/76)

## Has your plugin been signed previously?
yes

## Attach your plugin
[UltrawideUIFix.zip](https://github.com/openplanet-nl/plugin-signing/files/7959614/UltrawideUIFix.zip)

**Comment by codecat** [comment]
You probably want to add `siteid` and `version` to `info.toml`, see: https://openplanet.nl/tutorials/modern-plugins

**Comment by Eierpflanze** [comment]
Thanks, version was already in, but I added `siteid`.

Updated plugin:
[UltrawideUIFix.zip](https://github.com/openplanet-nl/plugin-signing/files/7966071/UltrawideUIFix.zip)

**Comment by codecat** [comment]
👍 

[UltrawideUIFix.zip](https://github.com/openplanet-nl/plugin-signing/files/7985711/UltrawideUIFix.zip)

**Comment by codecat** [comment]
Sorry, don't upload this yet, I gave you invalid signatures.

**Comment by codecat** [comment]
This one is correct 👍 

[UltrawideUIFix.zip](https://github.com/openplanet-nl/plugin-signing/files/7985832/UltrawideUIFix.zip)
