### ISSUE TITLE
Grinding Stats v1.5

### ISSUE THREAD

**Issue by drekdrek** [openplanet-nl/plugin-signing#175]
## Where can we find the plugin?
[[...]](https://openplanet.nl/files/158)

## Has your plugin been signed previously?
yes

## Attach your plugin
[Grinding Stats.zip](https://github.com/openplanet-nl/plugin-signing/files/7975163/Grinding.Stats.zip)

## Changelog
- added support for TM Turbo
- fixed file deletion functions

**Comment by codecat** [comment]
👍 

[GrindingStats.zip](https://github.com/openplanet-nl/plugin-signing/files/7985736/GrindingStats.zip)

FYI, this can be simplified:
```
IO::FromDataFolder("") + "Grinding Stats"
```
To:
```
IO::FromDataFolder("Grinding Stats")
```

**Comment by codecat** [comment]
Sorry, don't upload this yet, I gave you invalid signatures.

**Comment by codecat** [comment]
This one is correct 👍 

[GrindingStats.zip](https://github.com/openplanet-nl/plugin-signing/files/7985809/GrindingStats.zip)
