### ISSUE TITLE
Download Indicator 1.0

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#176]
## Plugin description
A user-friendly overview of what's going on in the background while you are playing. All background downloads are categorized in groups. Each group has its progress bar, with the group icon and color, showing the progress of the most recent download and the total percentage of the whole group being downloaded. On the right of a bar, you also see the amount of downloads for the group.

Plugin is meant to be used by everyone.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[DownloadIndicator.zip](https://github.com/openplanet-nl/plugin-signing/files/7978283/DownloadIndicator.zip)

**Comment by codecat** [comment]
Why are you loading `DroidSans.ttf`? It's supposed to be the default font: `@g_font = Resources::GetFont("DroidSans.ttf");`

👍 

[DownloadIndicator.zip](https://github.com/openplanet-nl/plugin-signing/files/7985887/DownloadIndicator.zip)
