### ISSUE TITLE
AFK Queue Tool 2.2.2

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#178]
## Where can we find the plugin?
https://openplanet.nl/files/71

## Has your plugin been signed previously?
yes

## Attach your plugin
[AFKQueue.zip](https://github.com/openplanet-nl/plugin-signing/files/7979574/AFKQueue.zip)

**Comment by Nsgr** [comment]
Had a bug report come in before this was signed, so version 2.2.3 now
[AFKQueue.zip](https://github.com/openplanet-nl/plugin-signing/files/7981890/AFKQueue.zip)

**Comment by codecat** [comment]
👍 

[AFKQueue.zip](https://github.com/openplanet-nl/plugin-signing/files/7985756/AFKQueue.zip)

**Comment by codecat** [comment]
Sorry, don't upload this yet, I gave you invalid signatures.

**Comment by codecat** [comment]
This one is correct 👍 

[AFKQueue.zip](https://github.com/openplanet-nl/plugin-signing/files/7985821/AFKQueue.zip)
