### ISSUE TITLE
Twitch Base 2.0.1

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#179]
## Where can we find the plugin?
https://openplanet.nl/files/93

## Has your plugin been signed previously?
yes

## Attach your plugin
[TwitchBase.zip](https://github.com/openplanet-nl/plugin-signing/files/7979621/TwitchBase.zip)

## Changes
- Removed "[Twitch]" prefix as the context is now shown in the log
- Fixed abandoning socket process due to timeout (previously, the connection was held anyway but since the API always responded this never resulted in a failed connection in the first place)

**Comment by codecat** [comment]
👍 

[TwitchBase.zip](https://github.com/openplanet-nl/plugin-signing/files/7985808/TwitchBase.zip)
