### ISSUE TITLE
Test Plugin

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#18]
## Plugin description
Just want to test, if I can show the authorTime of a Map on the Display. 

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
yes

## Did you use `Permissions.as`?
no
[Plugin_Test.zip](https://github.com/openplanet-nl/plugin-signing/files/6870909/Plugin_Test.zip)

**Comment by DennisWillers** [comment]
My fault - I think this request was too early

**Comment by codecat** [comment]
If you just want to test, I recommend getting the Club edition of the game so you can develop plugins without restrictions!

**Comment by DennisWillers** [comment]
I got the Club edition - just interpret the log files wrong
