### ISSUE TITLE
Dossard 1.0.0

### ISSUE THREAD

**Issue by jhett12321** [openplanet-nl/plugin-signing#180]
## Plugin description
Adds an adjustable UI element for the Dossard (`CSmScriptPlayer::Dossard`) - the number shown under the trigram on the back of your car.

![](https://i.imgur.com/IqeUAaf.png)

Plugin Page: https://openplanet.nl/files/166
GitHub: https://github.com/jhett12321/tm-dossard

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[Dossard.zip](https://github.com/openplanet-nl/plugin-signing/files/7980543/Dossard.zip)

**Comment by codecat** [comment]
Instead of using `Dev::GetOffsetUint32(playground.Interface, 0x1C)`, consider using `UI::IsGameUIVisible` instead.

👍 

[Dossard.zip](https://github.com/openplanet-nl/plugin-signing/files/7985849/Dossard.zip)
