### ISSUE TITLE
Download Indicator 1.2

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#181]
## Where can we find the plugin?
https://openplanet.nl/files/163

## Has your plugin been signed previously?
yes

## Attach your plugin
[DownloadIndicator.zip](https://github.com/openplanet-nl/plugin-signing/files/7987466/DownloadIndicator.zip)

**Comment by Nsgr** [comment]
Update before this was signed: Version 1.2.3:
[DownloadIndicator.zip](https://github.com/openplanet-nl/plugin-signing/files/7988725/DownloadIndicator.zip)

**Comment by codecat** [comment]
👍 

[DownloadIndicator.zip](https://github.com/openplanet-nl/plugin-signing/files/7990277/DownloadIndicator.zip)
