### ISSUE TITLE
Download Indicator 1.3.0

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#182]
## Where can we find the plugin?
https://openplanet.nl/files/163

## Has your plugin been signed previously?
yes

## Attach your plugin
[DownloadIndicator.zip](https://github.com/openplanet-nl/plugin-signing/files/7990778/DownloadIndicator.zip)

## Changes
- Change setting bool to enum what shows in the middle of the progress bar

**Comment by codecat** [comment]
👍 

[DownloadIndicator.zip](https://github.com/openplanet-nl/plugin-signing/files/7994992/DownloadIndicator.zip)
