### ISSUE TITLE
Grinding stats v1.5.1

### ISSUE THREAD

**Issue by drekdrek** [openplanet-nl/plugin-signing#183]
## Where can we find the plugin?
[[...]](https://openplanet.nl/files/158)

## Has your plugin been signed previously?
yes
## Attach your plugin
[Grinding Stats.zip](https://github.com/openplanet-nl/plugin-signing/files/7991192/Grinding.Stats.zip)

## Changelog
- changed function i was using for the `Always_except_when_interface_is_hidden` display settings

**Comment by codecat** [comment]
You forgot to update the version in `info.toml`.

I've fixed it for you. 👍 

[GrindingStats.zip](https://github.com/openplanet-nl/plugin-signing/files/7995021/GrindingStats.zip)
