### ISSUE TITLE
ItemExchange 1.0.1

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/plugin-signing#184]
## Where can we find the plugin?
[[...]](https://openplanet.nl/files/164)

## Has your plugin been signed previously?
yes

## Attach your plugin
[ItemExchange.zip](https://github.com/openplanet-nl/plugin-signing/files/7991412/ItemExchange.zip)

**Comment by codecat** [comment]
👍 

[ItemExchange.zip](https://github.com/openplanet-nl/plugin-signing/files/7995056/ItemExchange.zip)
