### ISSUE TITLE
Download Indicator 1.3.2

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#186]
## Where can we find the plugin?
https://openplanet.nl/files/163

## Has your plugin been signed previously?
yes

## Attach your plugin
[DownloadIndicator.zip](https://github.com/openplanet-nl/plugin-signing/files/7996418/DownloadIndicator.zip)

## Changes
- Bar center label now only is focused on single download as other downloads generally are sitting at 0B / 0B and just in some seconds actually have data
- Bar center label can be switched between size or progress
- Some helper function changes

**Comment by codecat** [comment]
👍 

[DownloadIndicator.zip](https://github.com/openplanet-nl/plugin-signing/files/8006706/DownloadIndicator.zip)
