### ISSUE TITLE
HUD Picker v1.1

### ISSUE THREAD

**Issue by DeafChips** [openplanet-nl/plugin-signing#187]
## Plugin description
https://openplanet.nl/files/168

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[HUDPicker.zip](https://github.com/openplanet-nl/plugin-signing/files/7996616/HUDPicker.zip)

**Comment by codecat** [comment]
👍 

[HUDPicker.zip](https://github.com/openplanet-nl/plugin-signing/files/8006711/HUDPicker.zip)
