### ISSUE TITLE
ItemExchange 1.0.2

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/plugin-signing#188]
## Where can we find the plugin?
https://openplanet.nl/files/164

## Has your plugin been signed previously?
yes

## changes
fix warnings
remove print spam
clean up code
fix font loading
limit set list to prevent many big picture loading

## Attach your plugin
(updated 2022-02-03T23:20:22.664Z)
[ItemExchange.zip](https://github.com/openplanet-nl/plugin-signing/files/7998921/ItemExchange.zip)

**Comment by codecat** [comment]
I don't think you actually fixed the font loading stuff with this, since you're still loading them as a static initializer rather than in `Main`.

[ItemExchange.zip](https://github.com/openplanet-nl/plugin-signing/files/8006745/ItemExchange.zip)

**Comment by RuurdBijlsma** [comment]
🤔For me the error was that I was loading fonts in a rendering context or something, this fixed the error for me. I'll move it to main for next release i guess
