### ISSUE TITLE
Author-Time Plugin

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#19]
## Plugin description
Show the author-time

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[AuthorTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6872410/AuthorTime.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[AuthorTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6872456/AuthorTime.zip)
