### ISSUE TITLE
Map Stats

### ISSUE THREAD

**Issue by oyv** [openplanet-nl/plugin-signing#191]
## Plugin description
https://github.com/oyv/tm-MapStats

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
~[MapStats.zip](https://github.com/openplanet-nl/plugin-signing/files/8007964/MapStats.zip)~

[MapStats.zip with siteid](https://github.com/openplanet-nl/plugin-signing/files/8010356/MapStats.zip)

**Comment by codecat** [comment]
If you intend to upload this to openplanet.nl, make sure you create a draft file on the site, and put the ID in `info.toml` (`siteid = x`) 👍 (This process will become much easier very very soon, sorry about that!)

Otherwise, let me know and I'll sign it regardless!

**Comment by oyv** [comment]
Oh, my bad. Uploaded with siteid now, thanks.

**Comment by codecat** [comment]
General announcement for all current plugin sign requests:

My current plan is to release a brand new Openplanet website tomorrow morning, which will be the new place for the plugin signing process. I won't be signing this right now, but when you see the new website tomorrow, please upload your plugin (to your existing plugin admin page), and we'll start the plugin review process from there! -- If the new site launch doesn't go as planned, I'll sign your plugin tomorrow morning regardless, but fingers crossed nothing goes wrong.. 🤞

**Comment by codecat** [comment]
Another general announcement for all current plugin sign requests:

The new website is now live! Log in to https://openplanet.dev/ and go to the [my plugins page](https://openplanet.dev/plugins/admin) to find your plugin admin panel, or submit a new plugin [here](https://openplanet.dev/plugins/admin/new) if you haven't created one yet. (Draft plugins have been migrated from the old site.)
