### ISSUE TITLE
Extra leaderboard positions V1.1

### ISSUE THREAD

**Issue by Banalian** [openplanet-nl/plugin-signing#192]
## Where can we find the plugin?
https://openplanet.nl/files/169

## Has your plugin been signed previously?
yes

## Attach your plugin
[ExtraLeaderboardPositions.zip](https://github.com/openplanet-nl/plugin-signing/files/8008915/ExtraLeaderboardPositions.zip)

## Changes
- Code cleanup
- Added pb to the list
- Should cover most edge case like being in the editor or on a map that isn't on nadeo's server
- Refresh every 5 minutes or when a new pb is set

**Comment by codecat** [comment]
👍 

[ExtraLeaderboardPositions.zip](https://github.com/openplanet-nl/plugin-signing/files/8009144/ExtraLeaderboardPositions.zip)
