### ISSUE TITLE
AFK Queue Tool 2.0 Beta 7

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#2]
## Where can we find the plugin?
https://openplanet.nl/files/71

## Has your plugin been signed previously?
[yes]

## Attach your plugin
[AFKQueue.zip](https://github.com/openplanet-nl/plugin-signing/files/6754981/AFKQueue.zip)

**Comment by codecat** [comment]
Looks good to me 👍 

[AFKQueue.zip](https://github.com/openplanet-nl/plugin-signing/files/6755085/AFKQueue.zip)
