### ISSUE TITLE
AITool Plugin signing

### ISSUE THREAD

**Issue by pporcher** [openplanet-nl/plugin-signing#20]
## Plugin description
Openplanet plugin for Trackmania 2020 that communicate with the outside world via socket and server to load map, save ghost and send telemetry.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[AITool.zip](https://github.com/openplanet-nl/plugin-signing/files/6873627/AITool.zip)

**Comment by codecat** [comment]
Starting an arbitrary map via `PlayMap` requires the permission `Permissions::PlayLocalMap` from `Permissions.as`. (Which I believe is in the Standard edition of the game?)

**Comment by pporcher** [comment]
Ah you are right ! `client_PlayLocalMap` permission requires Standard access.

**Comment by pporcher** [comment]
I modified my script and added the behavior you suggested on Discord of loading official campaign map by index.
I kept the option to load any arbitrary map but protected it with `Permissions::PlayLocalMap`.

## Plugin description
Openplanet plugin for Trackmania 2020 that communicate with the outside world via socket and server to load map, save ghost and send telemetry.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
**yes**

## Attach your plugin
[AITool.zip](https://github.com/openplanet-nl/plugin-signing/files/6874464/AITool.zip)

**Comment by codecat** [comment]
Thanks for the changes! 👍 

[AITool.zip](https://github.com/openplanet-nl/plugin-signing/files/6874803/AITool.zip)
