### ISSUE TITLE
Checkpoint Counter 2.0

### ISSUE THREAD

**Issue by Phlarx** [openplanet-nl/plugin-signing#21]
## Where can we find the plugin?
https://openplanet.nl/files/79

## Has your plugin been signed previously?
yes

## Attach your plugin
[CheckpointCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/6874319/CheckpointCounter.zip)

**Comment by Phlarx** [comment]
Oops, typoed the plugin name in the toml. Correct version:

[CheckpointCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/6874325/CheckpointCounter.zip)

**Comment by codecat** [comment]
Looks good 👍 

[CheckpointCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/6874782/CheckpointCounter.zip)
