### ISSUE TITLE
Personal-Best-Time

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#22]
## Plugin description
This Plugin shows your pb and the respective medal. In some Online Game modes like rank (3 vs 3) will be the pb not shown. 

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[personalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6874546/personalBestTime.zip)

**Comment by codecat** [comment]
This is the same plugin as #19, right? [This one](https://openplanet.nl/files/110)? You used the wrong Github issue template in that case 😅 

Also, consider adding `siteid = 110` to support automatic update checking.

**Comment by codecat** [comment]
Looks good 👍 

[PersonalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6874793/PersonalBestTime.zip)

**Comment by DennisWillers** [comment]
Thanks I will do it :)
