### ISSUE TITLE
Personal-Best-Time

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#23]
## Where can we find the plugin?
https://openplanet.nl/files/111

## Has your plugin been signed previously?
yes

## Attach your plugin
[PersonalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6881320/PersonalBestTime.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[PersonalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6881345/PersonalBestTime.zip)

**Comment by DennisWillers** [comment]
Ah shit I forgot to update the version in the info.toml... Do I need to make then again a new sign request?
