### ISSUE TITLE
Update Author-Time

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#24]
## Where can we find the plugin?
https://openplanet.nl/files/110

## Has your plugin been signed previously?
yes

## Attach your plugin
[AuthorTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6881428/AuthorTime.zip)

**Comment by DennisWillers** [comment]
Same here...  I forgot to update the version in the info.toml... I update here the Version. 1 Second please. Hopefully you didn´t signed it

**Comment by DennisWillers** [comment]
Edit the Zip-File with Version 1.1

**Comment by codecat** [comment]
Looks good! 👍 

[AuthorTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6881594/AuthorTime.zip)
