### ISSUE TITLE
Personal-Best-Time V1.2

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#26]
## Where can we find the plugin?
https://openplanet.nl/files/111

## Has your plugin been signed previously?
yes

## Attach your plugin
[PersonalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6887894/PersonalBestTime.zip)

## Info
Already tested by friends - Changed Version.

**Comment by codecat** [comment]
Didn't you already upload 1.2 on the website?

**Comment by codecat** [comment]
Here you go either way 👍 

[PersonalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6888850/PersonalBestTime.zip)

**Comment by DennisWillers** [comment]
Yeah I did, but that was the not signed Plugin. Thank you :) 
![image](https://user-images.githubusercontent.com/32564570/127230676-87655358-c90c-40d0-863e-dadb59f17be6.png)

**Comment by DennisWillers** [comment]
Now I uploaded in same Version, but as signed plugin. Hope that´s ok
