### ISSUE TITLE
Author-Time V1.2

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#28]
## Where can we find the plugin?
https://openplanet.nl/files/110

## Has your plugin been signed previously?
yes

## Attach your plugin
[AuthorTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6913126/AuthorTime.zip)

## Version change
- The player can position the window anywhere he wants. The state is remembered. Also the default settings can be reloaded.

**Comment by codecat** [comment]
Looks good 👍 

[AuthorTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6913484/AuthorTime.zip)
