### ISSUE TITLE
Personal-Best-Time V1.3

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#29]
## Where can we find the plugin?
https://openplanet.nl/files/111

## Has your plugin been signed previously?
yes

## Attach your plugin
[PersonalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6913132/PersonalBestTime.zip)

## Version changed
- After the player finishes, there is a 750ms wait for the new PB to load. Sometimes the new PB was not loaded because it was not yet saved in the Nadeo database.
- The player can position the window anywhere he wants. The state is remembered. Also the default settings can be reloaded.

**Comment by codecat** [comment]
Looks good! 👍 

[PersonalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/6913486/PersonalBestTime.zip)
