### ISSUE TITLE
Checkpoint Counter 1.7

### ISSUE THREAD

**Issue by Phlarx** [openplanet-nl/plugin-signing#3]
## Where can we find the plugin?
[https://openplanet.nl/files/79]

## Has your plugin been signed previously?
yes

## Attach your plugin
[Plugin_CheckpointCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/6755680/Plugin_CheckpointCounter.zip)

**Comment by codecat** [comment]
Looks good to me 👍 

[Plugin_CheckpointCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/6755686/Plugin_CheckpointCounter.zip)
