### ISSUE TITLE
Evo v1.2

### ISSUE THREAD

**Issue by Chris92de** [openplanet-nl/plugin-signing#30]
## Where can we find the plugin?
https://openplanet.nl/files/104

## Has your plugin been signed previously?
yes

## Attach your plugin
[Evo.zip](https://github.com/openplanet-nl/plugin-signing/files/6926031/Evo.zip)

**Comment by codecat** [comment]
Looks good 👍 

[Evo.zip](https://github.com/openplanet-nl/plugin-signing/files/6926539/Evo.zip)
