### ISSUE TITLE
Chat-Button-Bar

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#33]
## Description
*glhf*, *gg* or *nt* looks boring. With the Chat-Button-Bar you can bring **<span style="color:red">c</span><span style="color:yellow">o</span><span style="color:pink">l</span><span style="color:lightblue">o</span><span style="color:violet">r</span>** into the game. With a **single button click** you can send **predefined chat texts**. And if the predefined buttons are not enough, you can create your **own** standard texts.

## Features
- You can use up to 10 predefined text buttons
- Up to 20 buttons can be defined by yourself
- Change the position of the chat button bar by entering the X and Y coordinates
- Change the default and hover color of the buttons

## Limits
- You need the standard or club access
- The chat button bar is only displayed if Openplanet is not closed with F3.

![ChatButtonBar](https://user-images.githubusercontent.com/32564570/128628803-affad2c2-1267-4f15-9c4f-2b9afd168cf0.png)

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no ( I think so :D )

## Did you use `Permissions.as`?
yes

## Attach your plugin
[ChatButtonBar.zip](https://github.com/openplanet-nl/plugin-signing/files/6950541/ChatButtonBar.zip)

**Comment by codecat** [comment]
Consider adding `siteid = 115` under `version`, if you plan to upload this to Openplanet.nl. (115 is the next file ID, as shown [here](https://openplanet.nl/files).)

Your `Main.as` contains preprocessor directives that Openplanet will throw warnings about, plus your `Main()` function does nothing, so you could just remove that entire file.

Instead of resetting color in the menu with `\\$fff`, please use `\\$z` instead for consistency.

---

Also, the default texts are cool looking, BUT could be annoying for people in the server if **everyone** has this plugin and presses those buttons. It would be nice to change the defaults to something less obnoxious (eg. remove `$o` and `$s`, `$i`, etc. so only the colors remain), and let people configure to be obnoxious by themselves if they want to.

You should also add a time-out to the buttons so that people don't spam the chat full with gg's. Maybe make it so only 1 message per second can be sent?

**Comment by DennisWillers** [comment]
Changed everything with one different:
Only the button that the last time is pressed, can not be clicked for one second. Of course you can switch spaming between buttons. But if a spamer wants to spam, they will find a way.
[ChatButtonBar.zip](https://github.com/openplanet-nl/plugin-signing/files/6951271/ChatButtonBar.zip)

**Comment by codecat** [comment]
Why not make it a global timer? I'm not too worried about people "who want to spam", I'm more worried about literally everyone who gets their hands on this plug-in trying & starting to spam.

**Comment by DennisWillers** [comment]
There are use cases in which two different buttons want to be pressed one after the other. For example *Hi* and *GlHf*, or *GG* and *BB*. To wait a second to press a button can feel very long. Especially if you have not much time between races like in 3 vs 3. But you don´t need to spam the same button always, that´s why I implement that the same button can not pressed again in less than one second.  
But even a second doesn't stop people from trying every button when they have the plugin installed for the first time. So I think, I would just implement something, that just makes the plugin a bit more annoying for the user as it should be. And if we are honest, this plugin will not become as popular as your dashboard ;). 
If you tell me you'll sign the plugin only if I add this global one second timer, then I'll do it. But I prefer the solution with just not pressing the same button in less than a second.

**Comment by codecat** [comment]
Good point, I didn't think of that. Just checked the code, you could still really quickly spam by pressing 1 button, then the other, then the first one, etc. Might not be a huge problem though.

> this plugin will not become as popular

Well, who knows 🙃 this seems like a really cool plugin to feature as well, and I don't really want to end up in a situation where a ton of people have this plugin and the chat becomes super obnoxious. Seems like a tough responsibility to have to me 😅 

But with the plugin manager, updating plugins has become super easy anyway, so it can always be updated in the future.

Here you go! 👍 
[ChatButtonBar.zip](https://github.com/openplanet-nl/plugin-signing/files/6953752/ChatButtonBar.zip)

**Comment by DennisWillers** [comment]
Thanks! :)
> Good point, I didn't think of that. Just checked the code, you could still really quickly spam by pressing 1 button, then the other, then the first one, etc. Might not be a huge problem 

If you want I can try to fix this bug after work too. Should be possible with a list. Don´t want that you have a bad feeling about it. 👀

**Comment by codecat** [comment]
That would be great!

**Comment by DennisWillers** [comment]
[ChatButtonBar.zip](https://github.com/openplanet-nl/plugin-signing/files/6957356/ChatButtonBar.zip)

Should be fixed now :) Hopefully you see this message, even if this issue is closed :P

**Comment by codecat** [comment]
The logic in `checkIfButtonsCanNotBeClicked` seems a bit weird to me, it probably won't work the way you expect, but it's good enough. Thanks!

[ChatButtonBar.zip](https://github.com/openplanet-nl/plugin-signing/files/6960999/ChatButtonBar.zip)
