### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/plugin-signing#34]
## Where can we find the plugin?
https://openplanet.nl/files/70
https://github.com/skybaks/color-picker

## Has your plugin been signed previously?
yes

## Attach your plugin
[ColorPicker_ForSigning.zip](https://github.com/openplanet-nl/plugin-signing/files/6965323/ColorPicker_ForSigning.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[ColorPicker.zip](https://github.com/openplanet-nl/plugin-signing/files/6973990/ColorPicker.zip)

**Comment by skybaks** [comment]
Thanks as always! :)
