### ISSUE TITLE
Ghost to Replay

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/plugin-signing#35]
## Where can we find the plugin?
https://openplanet.nl/files/62
https://github.com/skybaks/ghost-to-replay

## Has your plugin been signed previously?
yes

## Attach your plugin
[ghost_to_replay_sig_req.zip](https://github.com/openplanet-nl/plugin-signing/files/6965357/ghost_to_replay_sig_req.zip)

**Comment by codecat** [comment]
Previously, this plugin had `#perms "paid"`, is there an appropriate permission in `Permissions.as` to use for this? Maybe `CreateLocalReplay` and/or `OpenReplayEditor`?

**Comment by skybaks** [comment]
Great thought! I will implement that.

**Comment by skybaks** [comment]
[GhostToReplay.zip](https://github.com/openplanet-nl/plugin-signing/files/6979570/GhostToReplay.zip)

* Added permission checks.
* Did some more testing, accessing `Nickname` is no longer a script crash!
* Also, with the more testing, invalid urls dont crash game anymore. (Thanks Nadeo! 😄 )

**Comment by codecat** [comment]
Thanks! Looks good 👍 

[GhostToReplay.zip](https://github.com/openplanet-nl/plugin-signing/files/6981911/GhostToReplay.zip)
