### ISSUE TITLE
Borders v0.1

### ISSUE THREAD

**Issue by DergnNamedSkye** [openplanet-nl/plugin-signing#36]
## Plugin description
> Plugin that creates virtual borders around the screen. Helpful for imitating arbitrary resolutions like 4:3 without stretching your resolution!

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
No.

## Did you use `Permissions.as`?
No.

## Attach your plugin
[GitHub Repository](https://github.com/DergnNamedSkye/op-borders)
[Borders.zip](https://github.com/openplanet-nl/plugin-signing/files/6975781/Borders.zip)

**Comment by DergnNamedSkye** [comment]
Plugin is crashing after the update, investigating and then resubmitting a new version soon.

**Comment by codecat** [comment]
Looks good 👍 

[Borders.zip](https://github.com/openplanet-nl/plugin-signing/files/6981895/Borders.zip)

Consider adding `siteid` to `[meta]` if you intend to upload this to Openplanet.nl (this means I have to re-sign `info.toml` too)

**Comment by DergnNamedSkye** [comment]
Here's the `info.toml` with `siteid = 116`.
[info_borders.txt](https://github.com/openplanet-nl/plugin-signing/files/6982621/info_borders.txt)

**Comment by codecat** [comment]
👍 

[info.toml.zip](https://github.com/openplanet-nl/plugin-signing/files/6982639/info.toml.zip)

**Comment by DergnNamedSkye** [comment]
Whoops, my bad.
[info_borders.txt](https://github.com/openplanet-nl/plugin-signing/files/6982657/info_borders.txt)

**Comment by codecat** [comment]
[info.toml.zip](https://github.com/openplanet-nl/plugin-signing/files/6985467/info.toml.zip)

**Comment by DergnNamedSkye** [comment]
I've been sabotaged by [this](https://openplanet.nl/files/116) plugin and had to update the `siteid` again 😅
[info.toml.txt](https://github.com/openplanet-nl/plugin-signing/files/6986342/info.toml.txt)

**Comment by codecat** [comment]
Fixed 👍 

[info.toml.zip](https://github.com/openplanet-nl/plugin-signing/files/6986347/info.toml.zip)

**Comment by DergnNamedSkye** [comment]
I'm sorry, this is [ridiculous](https://openplanet.nl/files/118) at this point. I'll be uploading my new plugins without signatures first from now on, didn't know you could do that (according to some users).

[info.toml.txt](https://github.com/openplanet-nl/plugin-signing/files/6986417/info.toml.txt)

**Comment by codecat** [comment]
Handled in DM 👍
