### ISSUE TITLE
Screenshooter v0.1

### ISSUE THREAD

**Issue by DergnNamedSkye** [openplanet-nl/plugin-signing#37]
## Plugin description
> Plugin that enhances in-game screenshot feature. The big advantage is the ability to take 360 panoramas!

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
No.

## Did you use `Permissions.as`?
No.

## Attach your plugin
[GitHub Mirror](https://github.com/DergnNamedSkye/op-screenshooter)
[Screenshooter.zip](https://github.com/openplanet-nl/plugin-signing/files/6980163/Screenshooter.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[Screenshooter.zip](https://github.com/openplanet-nl/plugin-signing/files/6981951/Screenshooter.zip)

Consider adding `siteid` to `[meta]` if you intend to upload this to Openplanet.nl (this means I have to re-sign info.toml too)

**Comment by DergnNamedSkye** [comment]
Here's the info.toml with siteid = 117.
[info_screenshooter.txt](https://github.com/openplanet-nl/plugin-signing/files/6982632/info_screenshooter.txt)

**Comment by codecat** [comment]
[info.toml.zip](https://github.com/openplanet-nl/plugin-signing/files/6985465/info.toml.zip)
