### ISSUE TITLE
New plugin signature request: Extract Validation Replay

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/plugin-signing#38]
## Plugin description
Takes the ghost embedded in current `RootMap` and saves it to a replay in the users downloads folder.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
yes

## Attach your plugin
[ExtractValidationReplay.zip](https://github.com/openplanet-nl/plugin-signing/files/6985139/ExtractValidationReplay.zip)

**Comment by codecat** [comment]
Looks good 👍 

[ExtractValidationReplay.zip](https://github.com/openplanet-nl/plugin-signing/files/6985477/ExtractValidationReplay.zip)
