### ISSUE TITLE
Plugin Update: Editor Helpers

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/plugin-signing#41]
## Where can we find the plugin?
https://openplanet.nl/files/69
https://github.com/skybaks/editor-helpers

## Has your plugin been signed previously?
yes

## What did you change?
* Continued breakup of megalithic single file plugin.
* Added support for MP4 by adding a Compatibility namespace to each class that did not translate exactly.

## Attach your plugin
[EditorHelpers.zip](https://github.com/openplanet-nl/plugin-signing/files/6987255/EditorHelpers.zip)

**Comment by codecat** [comment]
Looks good 👍 

[EditorHelpers.zip](https://github.com/openplanet-nl/plugin-signing/files/6988283/EditorHelpers.zip)
