### ISSUE TITLE
Voting Plugin

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#44]
## Description
Finally you have the possibility to **vote tracks!** As you may know it from *TMN*, you can give ratings from **---** to **+++** via chat or via the plugin. You will also see how many players have voted for the map in total. In addition, the average rating is displayed in stars and in a number. This is a **global** vote manager. It doesn't matter if you play solo or on a server. You can always see the current voting status of the current map.

## Features
- You can give the following ratings: **---**, **--**, **-**, **+**, **++**, **+++**
- The vote can be given via the **plugin** or via the **chat**
- The **number of players** who have given a vote is displayed.
- The **average rating** is displayed in the form of a **number**
- The **average rating** is displayed in the form of **stars**.
- It can be set in the **settings** that the title bar is displayed. The **position** of the voting plugin can also be adjusted by dragging the title bar.
- You can set in the **settings** that **no chat message** should be sent when clicking on a vote in the voting plugin.
- The plugin can be **hidden** via the script tab.

## Limits
- If Openplanet is hidden with F3 no rating can be given over the plugin. It is still possible via the chat window. In the alternative view, the last submitted rating is displayed.
- Currently, a maximum of 500 simultaneous connections are allowed with the plugin. If this plugin will be used by many people, this number could be changed upwards.

## Star definition
The following star scale was defined for the voting plugin:

| Scale | Stars 
| -----|:--:|
| 92-100 | 5 |
| 83-91 | 4.5 |
| 74-82 | 4 |
| 64-73 | 3.5 |
| 55-63 | 3 |
| 45-54 | 2.5 |
| 36-44 | 2 |
| 27-35 | 1.5 |
| 18-26 | 1 |
| 9-17 | 0.5 |
| 0-8 | 0 |

## Source Code
The source code for the backend project can be found here:
https://git.willers.digital/Dennis.Willers/voting

The source code for the plugin can be found here:
https://git.willers.digital/Dennis.Willers/voting-plugin

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[Voting.zip](https://github.com/openplanet-nl/plugin-signing/files/7033101/Voting.zip)

**Comment by codecat** [comment]
There's a `.op` file in your `.op` file 😅 

You didn't want to reserve a site ID for this plugin?

Also side note, you do `.get_Length()` instead of `.Length`.

**Comment by DennisWillers** [comment]
Hups 😅
Yeah I can reserve an ID. I do it when I'm back home :)
What is the different between Get_Length() and Length() ?

**Comment by codecat** [comment]
There's no difference in functionality, but when a method is prefixed with `get_`, that means it's a property getter that you can just get as if it were a property.

**Comment by DennisWillers** [comment]
Changed it :)
I forgot to add at one place a permission question. I have add it now. 
So: "Did you provide a perms meta value or a #perms preprocessor option?" YES

[Voting.zip](https://github.com/openplanet-nl/plugin-signing/files/7034630/Voting.zip)

**Comment by codecat** [comment]
You didn't actually reserve the ID 😅 But that's okay, here's the signed plugin:

[Voting.zip](https://github.com/openplanet-nl/plugin-signing/files/7039469/Voting.zip)

If you want to actually reserve an ID, you can just click to upload a new plugin on the site and mark it as a draft. 👍

**Comment by DennisWillers** [comment]
Thank you! I will remember for next time :)
