### ISSUE TITLE
Plugin signature request: "Force Display Mode"

### ISSUE THREAD

**Issue by Ze-Rax** [openplanet-nl/plugin-signing#46]
## Plugin description
https://openplanet.nl/files/122
Force Display Mode is a simple plugin, that changes the display mode of the game (fullscreen, windowed, windowed borderless) to the mode specified in the settings in openplanet. The reason for this to exist is, that sometimes the game changes from fullscreen to windowed borderless by itself (for example when tabbing out while loading a map).

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
Plugin attached as a zip, as github doesn't support attaching it as .op
[ForceDisplayMode.zip](https://github.com/openplanet-nl/plugin-signing/files/7067136/ForceDisplayMode.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[ForceDisplayMode.zip](https://github.com/openplanet-nl/plugin-signing/files/7070684/ForceDisplayMode.zip)
