### ISSUE TITLE
New signature request: TMX Randomizer

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#47]
## Plugin description
It takes randomly a map from (T)MX and plays it
Source code here: https://github.com/GreepTheSheep/openplanet-mx-random

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
yes, a "paid" permission in info.toml

## Did you use `Permissions.as`?
no (edit: yes)

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7069659/MXRandom.zip)

**Comment by codecat** [comment]
It doesn't look like you're actually checking any permission in your scripts?

**Comment by GreepTheSheep** [comment]
:/ I'm little lost on that, can you help me on this ?

**Comment by GreepTheSheep** [comment]
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7070785/MXRandom.zip)

That's now the good one :p

**Comment by codecat** [comment]
FYI: This is not necessary:
```angelscript
Headers["User-Agent"] = "Openplanet" /* add here OP version */ + " " + name + "/" + Meta::ExecutingPlugin().get_Version();
```
Openplanet adds a user agent pretty similar to this by default (which also includes the Openplanet version, as well as the plugin name & version.

**Comment by codecat** [comment]
I'll sign it regardless 👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7077665/MXRandom.zip)
