### ISSUE TITLE
Update MXRandom (fix errors)

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#48]
## Where can we find the plugin?
https://github.com/GreepTheSheep/openplanet-mx-random

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7078242/MXRandom.zip)

**Comment by codecat** [comment]
Looks good 👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7079975/MXRandom.zip)
