### ISSUE TITLE
Plugin signature: Events Reminder

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#49]
## Plugin description
Reminds you in-game about COTD and Super Royal events upcoming in Trackmania 
![Reminder COTD](https://imgur.com/Pqn153p.png)

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
yes, for COTD events reminder only

## Did you use `Permissions.as`?
yes

## Attach your plugin
[Reminder.zip](https://github.com/openplanet-nl/plugin-signing/files/7080167/Reminder.zip)

**Comment by GreepTheSheep** [comment]
Had to update siteid
[Reminder.zip](https://github.com/openplanet-nl/plugin-signing/files/7082152/Reminder.zip)

**Comment by codecat** [comment]
👍 

[Reminder.zip](https://github.com/openplanet-nl/plugin-signing/files/7083581/Reminder.zip)
