### ISSUE TITLE
Quick Link Opener 1.1

### ISSUE THREAD

**Issue by AmazingBeu** [openplanet-nl/plugin-signing#5]
## Where can we find the plugin?
https://openplanet.nl/files/101

## Has your plugin been signed previously?
yes

## Attach your plugin
[QuickLinkOpener.zip](https://github.com/openplanet-nl/plugin-signing/files/6756236/QuickLinkOpener.zip)

## What's changed
* compatibility for OP 1.18.7

**Comment by codecat** [comment]
Looks good 👍 

[QuickLinkOpener.zip](https://github.com/openplanet-nl/plugin-signing/files/6756307/QuickLinkOpener.zip)
