### ISSUE TITLE
fix error (again) on MXRandom

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#50]
Note: Still having errors with the `#if TMNEXT` preprocessor, it's my fault I'm too bad... sorry for begging you again :/

## Where can we find the plugin?
https://github.com/GreepTheSheep/openplanet-mx-random

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7080183/MXRandom.zip)

**Comment by codecat** [comment]
👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7083567/MXRandom.zip)
