### ISSUE TITLE
Accelerometer by zayshaa

### ISSUE THREAD

**Issue by ZayshaaCodes** [openplanet-nl/plugin-signing#51]
## Plugin description
Observes the change in speed to give a visual bar or graph HUD for acceleration.
Largely built around Dashboard as a template.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[tm-accelerometer.zip](https://github.com/openplanet-nl/plugin-signing/files/7080986/tm-accelerometer.zip)

**Comment by codecat** [comment]
👍 

Ps: Please keep in mind you have to maintain Dashboard's vehicle code if you want your plugin to continue being stable with future game updates!

[Accelerometer.zip](https://github.com/openplanet-nl/plugin-signing/files/7083644/Accelerometer.zip)

**Comment by ZayshaaCodes** [comment]
Understood. Thank you! <3
