### ISSUE TITLE
Plugin update: MXRandom 1.1

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#54]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7108496/MXRandom.zip)

**Comment by codecat** [comment]
Looks good 👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7109733/MXRandom.zip)
