### ISSUE TITLE
Tweaker v0.01

### ISSUE THREAD

**Issue by DergnNamedSkye** [openplanet-nl/plugin-signing#55]
## Plugin description
Helps modify in-game hidden settings and boost the performance.
Currently can change only two options:
- Render distance
- Level of detail

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
No.

## Did you use `Permissions.as`?
No.

## Attach your plugin
[Tweaker.zip](https://github.com/openplanet-nl/plugin-signing/files/7108842/Tweaker.zip)

**Comment by codecat** [comment]
Will this only work on TM? What about Maniaplanet? Does changing the Z clip allow people to potentially "cheat" by "wallhacking" in Shootmania or any TM hide and seek game?

**Comment by DergnNamedSkye** [comment]
Toggling *Z clip* in *ManiaPlanet* is different and doesn't work with this plugin though it is easier and immediate (`Viewport.Cameras[1].ZClipValue`) but I didn't implement it yet. I doubt it affects *hide&seek* modes because *Z clip* applies on a global scale and I didn't see any mode utilizing this value. If any mode will be discovered that uses this feature I'll block it if needed.

*ManiaPlanet* errors:

![image](https://user-images.githubusercontent.com/88372586/132094876-560011ae-d62b-48a6-acf0-f4e0715fce56.png)

**Comment by codecat** [comment]
Looks good 👍 

[Tweaker.zip](https://github.com/openplanet-nl/plugin-signing/files/7109793/Tweaker.zip)
