### ISSUE TITLE
ManiaExchange Button 1.1

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#56]
## Where can we find the plugin?
https://openplanet.nl/files/88

## Has your plugin been signed previously?
[yes]

## Attach your plugin
[ExchangeButton.zip](https://github.com/openplanet-nl/plugin-signing/files/7111796/ExchangeButton.zip)

**Comment by codecat** [comment]
👍 

[ExchangeButton.zip](https://github.com/openplanet-nl/plugin-signing/files/7111986/ExchangeButton.zip)
