### ISSUE TITLE
Update: MXRandom 1.2.1

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#59]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7114057/MXRandom.zip)

**Comment by codecat** [comment]
Looks good 👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7114301/MXRandom.zip)
