### ISSUE TITLE
Joinbug Workaround 1.1

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#6]
## Where can we find the plugin?
https://openplanet.nl/files/75

## Has your plugin been signed previously?
yes

## Attach your plugin
[JoinbugWorkaround.zip](https://github.com/openplanet-nl/plugin-signing/files/6756386/JoinbugWorkaround.zip)

**Comment by codecat** [comment]
Looks good 👍 

[JoinbugWorkaround.zip](https://github.com/openplanet-nl/plugin-signing/files/6757292/JoinbugWorkaround.zip)
