### ISSUE TITLE
Update MXRandom 1.2.2 (quick fix)

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#60]
1.2.1 has a bug that is fixed on 1.2.2

## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7116830/MXRandom.zip)

**Comment by codecat** [comment]
👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7117130/MXRandom.zip)
