### ISSUE TITLE
Blocks&ItemsCounter 1.1

### ISSUE THREAD

**Issue by AmazingBeu** [openplanet-nl/plugin-signing#63]
## Where can we find the plugin?
https://openplanet.nl/files/97

## Has your plugin been signed previously?
yes

## Attach your plugin
[Blocks&ItemsCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/7123036/Blocks.ItemsCounter.zip)

## Changes:
* Fix cam focus of blocks placed in free mapping
* add color depending of the trigger (CP, start,...)
* Improve support with MP4
* Use the new plugin file format

## Git diff:
https://git.virtit.fr/beu/Openplanet-Plugins/commit/2724f54ce82b9676dcbb8bbdda6fff5e54b3baf4

**Comment by codecat** [comment]
👍 

[Blocks&ItemsCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/7124705/Blocks.ItemsCounter.zip)
