### ISSUE TITLE
Accelerometer 0.2

### ISSUE THREAD

**Issue by ZayshaaCodes** [openplanet-nl/plugin-signing#64]
## Where can we find the plugin?
https://openplanet.nl/files/123

## Has your plugin been signed previously?
yes

## Attach your plugin
[Accelerometer.zip](https://github.com/openplanet-nl/plugin-signing/files/7126765/Accelerometer.zip)

<3

**Comment by codecat** [comment]
Sorry for the delay 👍 

[Accelerometer.zip](https://github.com/openplanet-nl/plugin-signing/files/7138234/Accelerometer.zip)
