### ISSUE TITLE
ManiaExchange Button 1.2

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#66]
## Where can we find the plugin?
https://openplanet.nl/files/88

## Has your plugin been signed previously?
yes

## Attach your plugin
[ExchangeButton.zip](https://github.com/openplanet-nl/plugin-signing/files/7135286/ExchangeButton.zip)

**Comment by Nsgr** [comment]
Updated file due to misunderstood feature request by user (ver 1.3 now)

[ExchangeButton.zip](https://github.com/openplanet-nl/plugin-signing/files/7135563/ExchangeButton.zip)

**Comment by codecat** [comment]
Looks good 👍 

[ExchangeButton.zip](https://github.com/openplanet-nl/plugin-signing/files/7138263/ExchangeButton.zip)
