### ISSUE TITLE
ManiaExchange Button 1.3.1

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/plugin-signing#67]
## Where can we find the plugin?
https://openplanet.nl/files/88

## Has your plugin been signed previously?
yes

## Attach your plugin
[ExchangeButton.zip](https://github.com/openplanet-nl/plugin-signing/files/7138975/ExchangeButton.zip)

**Comment by codecat** [comment]
👍 

[ExchangeButton.zip](https://github.com/openplanet-nl/plugin-signing/files/7139023/ExchangeButton.zip)
