### ISSUE TITLE
Update: ForceDisplayMode 1.0.2

### ISSUE THREAD

**Issue by Ze-Rax** [openplanet-nl/plugin-signing#68]
## Where can we find the plugin?
Previous version: https://openplanet.nl/files/122
Fixed an issue to make it work (not crash on startup) for Maniaplanet.

## Has your plugin been signed previously?
yes

## Attach your plugin
[ForceDisplayMode.zip](https://github.com/openplanet-nl/plugin-signing/files/7139863/ForceDisplayMode.zip)

**Comment by codecat** [comment]
👍 

[ForceDisplayMode.zip](https://github.com/openplanet-nl/plugin-signing/files/7139960/ForceDisplayMode.zip)
