### ISSUE TITLE
New: Flinks Challenge

### ISSUE THREAD

**Issue by thebirk** [openplanet-nl/plugin-signing#69]
## Plugin description
A timer and medal tracker for aiding in the doing Flinks random map challenge, https://flinkblog.de/RMC/ . 
Draft - https://openplanet.nl/files/128

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[FlinksChallenge.zip](https://github.com/openplanet-nl/plugin-signing/files/7140088/FlinksChallenge.zip)

**Comment by codecat** [comment]
Looks good! 👍 

[FlinksChallenge.zip](https://github.com/openplanet-nl/plugin-signing/files/7140368/FlinksChallenge.zip)
