### ISSUE TITLE
NitroDashboard v1.2.0

### ISSUE THREAD

**Issue by nitroquery** [openplanet-nl/plugin-signing#7]
## Where can we find the plugin?

https://github.com/nitroquery/NitroDashboard/releases/tag/v1.2.0

## Has your plugin been signed previously?
- [x] yes

## Attach your plugin

[NitroDashboard.zip](https://github.com/nitroquery/NitroDashboard/releases/download/v1.2.0/NitroDashboard.zip)

**Comment by codecat** [comment]
Looks good 👍 

[NitroDashboard.zip](https://github.com/openplanet-nl/plugin-signing/files/6758725/NitroDashboard.zip)
