### ISSUE TITLE
Voting - Version 1.1

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#71]
## Where can we find the plugin?
https://openplanet.nl/files/120

## Has your plugin been signed previously?
yes

## Changes
- You can now set the value 0 on the position X axis. Before, the default value was set automatically.
- If the voting backend server is not available, a message is displayed.
- In the settings you can now set if the voting plugin should be displayed. This setting can also be made via the menu. This setting is persistent.
- In the track editor mode, the plugin is only displayed if a valid time has been driven.

## Attach your plugin
[Voting.zip](https://github.com/openplanet-nl/plugin-signing/files/7146513/Voting.zip)

**Comment by codecat** [comment]
👍 

[Voting.zip](https://github.com/openplanet-nl/plugin-signing/files/7148007/Voting.zip)
