### ISSUE TITLE
Author-Time - Version 1.3

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#72]
## Where can we find the plugin?
https://openplanet.nl/files/110

## Has your plugin been signed previously?
yes

## Changes
- The menu icon was replaced
- In the settings you can now set if the Author-Time plugin should be displayed. This setting can also be made via the menu. This setting is persistent.
- In track editor mode, the random time is no longer displayed. Either it is displayed that there is no AT yet, or the AT is displayed as soon as navigating back to the editor mode after the validation drive.

## Attach your plugin
[AuthorTime.zip](https://github.com/openplanet-nl/plugin-signing/files/7146556/AuthorTime.zip)

**Comment by codecat** [comment]
👍 

[AuthorTime.zip](https://github.com/openplanet-nl/plugin-signing/files/7148009/AuthorTime.zip)
