### ISSUE TITLE
Personal-Best-Time - Version 1.4

### ISSUE THREAD

**Issue by DennisWillers** [openplanet-nl/plugin-signing#73]
## Where can we find the plugin?
https://openplanet.nl/files/111

## Has your plugin been signed previously?
yes

## Changes
- The menu icon was replaced
- In the settings you can now set if the Personal-Best-Time plugin should be displayed. This setting can also be made via the menu. This setting is persistent.

## Attach your plugin
[PersonalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/7146562/PersonalBestTime.zip)

**Comment by codecat** [comment]
👍 

[PersonalBestTime.zip](https://github.com/openplanet-nl/plugin-signing/files/7148011/PersonalBestTime.zip)
