### ISSUE TITLE
Update: ForceDisplayMode 1.0.3

### ISSUE THREAD

**Issue by Ze-Rax** [openplanet-nl/plugin-signing#77]
## Where can we find the plugin?
https://openplanet.nl/files/122
Had to change where DisplaySettings handle is obtained, due to Maniaplanet replacing DisplaySettings after startup.

## Has your plugin been signed previously?
yes

## Attach your plugin
[ForceDisplayMode.zip](https://github.com/openplanet-nl/plugin-signing/files/7147666/ForceDisplayMode.zip)

**Comment by codecat** [comment]
`siteid` is defined in this toml as a string, that might cause problems.

I have modified it in the below package for you already 👍 

[ForceDisplayMode.zip](https://github.com/openplanet-nl/plugin-signing/files/7148022/ForceDisplayMode.zip)
