### ISSUE TITLE
Update: MXRandom 1.4 (dev branch)

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#78]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom-dev.zip](https://github.com/openplanet-nl/plugin-signing/files/7148800/MXRandom-dev.zip)

**Comment by codecat** [comment]
👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7148836/MXRandom.zip)
