### ISSUE TITLE
Update: MXRandom 1.4.1 (bugs fix)

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#79]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom-dev.zip](https://github.com/openplanet-nl/plugin-signing/files/7149213/MXRandom-dev.zip)
Fixed a "not a member" on 2020 because I forgot, and also added a setting for the UI

**Comment by codecat** [comment]
Oh, I somehow missed this, sorry for the delay 👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7158095/MXRandom.zip)
