### ISSUE TITLE
Distance Counter 1.3

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#8]
## Where can we find the plugin?
https://openplanet.nl/files/81

## Has your plugin been signed previously?
yes

## Attach your plugin
[DistanceCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/6758708/DistanceCounter.zip)

**Comment by codecat** [comment]
Looks good 👍 

[DistanceCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/6758727/DistanceCounter.zip)

**Comment by GreepTheSheep** [comment]
Did a mistake on the toml file
[DistanceCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/6758831/DistanceCounter.zip)

**Comment by codecat** [comment]
Fixed 👍 

[DistanceCounter.zip](https://github.com/openplanet-nl/plugin-signing/files/6758852/DistanceCounter.zip)
