### ISSUE TITLE
Drive Alone

### ISSUE THREAD

**Issue by xPaw** [openplanet-nl/plugin-signing#82]
## Plugin description
Automatically click "Drive Alone" when loading a map in Solo to avoid selecting a ghost to race against.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
https://openplanet.nl/files/132

**Comment by codecat** [comment]
Looks good! 👍 

[DriveAlone.zip](https://github.com/openplanet-nl/plugin-signing/files/7161403/DriveAlone.zip)
