### ISSUE TITLE
MXRandom fix errors made by me

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#84]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7163525/MXRandom.zip)
(fixed problem with current time and wrong timer when starting)

**Comment by codecat** [comment]
👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7164389/MXRandom.zip)
