### ISSUE TITLE
MXRandom 1.4.2 (patch)

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#87]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7172748/MXRandom.zip)
(fixed not autoskip if time exactly the same as AT, and replace font to an monospace font)

*also it is possible to have the plugin dev role on the discord?* 👉👈

**Comment by codecat** [comment]
👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7173756/MXRandom.zip)
