### ISSUE TITLE
Join server by address 1.2

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#9]
## Where can we find the plugin?
https://openplanet.nl/files/90

## Has your plugin been signed previously?
yes

## Attach your plugin
[JoinServerIP.zip](https://github.com/openplanet-nl/plugin-signing/files/6758710/JoinServerIP.zip)

**Comment by codecat** [comment]
Looks good 👍 

[JoinServerIP.zip](https://github.com/openplanet-nl/plugin-signing/files/6758729/JoinServerIP.zip)

**Comment by GreepTheSheep** [comment]
Reopened because I did a mistake on the info.toml file
[JoinServerIP.zip](https://github.com/openplanet-nl/plugin-signing/files/6758827/JoinServerIP.zip)

**Comment by codecat** [comment]
Fixed 👍 

[JoinServerIP.zip](https://github.com/openplanet-nl/plugin-signing/files/6758849/JoinServerIP.zip)
