### ISSUE TITLE
Update MXRandom 1.5

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#90]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7192426/MXRandom.zip)

[Changelog](https://github.com/GreepTheSheep/openplanet-mx-random/pull/19)

**Comment by codecat** [comment]
👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7192891/MXRandom.zip)
