### ISSUE TITLE
MXRandom 1.5.1 (fix typo)

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#92]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7203794/MXRandom.zip)

**Comment by codecat** [comment]
👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7204475/MXRandom.zip)
