### ISSUE TITLE
MXRandom dev

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/plugin-signing#95]
## Where can we find the plugin?
https://openplanet.nl/files/124

## Has your plugin been signed previously?
yes

## Attach your plugin
[MXRandom-dev.zip](https://github.com/openplanet-nl/plugin-signing/files/7231214/MXRandom-dev.zip)

**Comment by codecat** [comment]
👍 

[MXRandom.zip](https://github.com/openplanet-nl/plugin-signing/files/7231289/MXRandom.zip)

Ps: if this is signed just so you can test the plugin yourself, yet again, please consider getting Club Edition
