### ISSUE TITLE
Ghost Scrubber

### ISSUE THREAD

**Issue by boofat** [openplanet-nl/plugin-signing#97]
## Plugin description
Allows you to seek ghosts while playing and view your current run. Only works in Solo mode.

https://openplanet.nl/files/136

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[GhostScrubber.zip](https://github.com/openplanet-nl/plugin-signing/files/7256214/GhostScrubber.zip)

**Comment by codecat** [comment]
```asc
bool CanAddGhosts() {
    return true;
    // return Permissions::PlayRecords();
}
```
This seems wrong?

**Comment by boofat** [comment]
That was pulled out of a plugin that could add arbitrary ghosts where checking PlayRecords makes perfect sense, but with this plugin the only ghost added is a "Current race" one which seemed more analogous to a personal best. Though it's no problem to rework it and check permissions.

**Comment by codecat** [comment]
Oh I see. So w/o the permission you'd only be able to scrub through your PB ghost?

**Comment by boofat** [comment]
Yeah, your PB ghost or any others added externally (Records widget or through the menu.)

And sure, removed that function and a couple filename ones, but the rest is the same functionally: [GhostScrubber.zip](https://github.com/openplanet-nl/plugin-signing/files/7262968/GhostScrubber.zip)

**Comment by codecat** [comment]
Thanks for the changes! 👍  Sorry for the delay 😅 

[GhostScrubber.zip](https://github.com/openplanet-nl/plugin-signing/files/7271323/GhostScrubber.zip)
